// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsRht_GM1V_5QftkYSDG18_zGfFy4KwnY',
    appId: '1:288869750518:web:413e8bbd07286f1a73bed7',
    messagingSenderId: '288869750518',
    projectId: 'university-system-24232',
    authDomain: 'university-system-24232.firebaseapp.com',
    storageBucket: 'university-system-24232.firebasestorage.app',
    measurementId: 'G-ZF6BQPYSWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTbYkLx9XWqsHIp_R0M6MpcZiMEiCeH4Y',
    appId: '1:288869750518:android:7213fa17f93de39d73bed7',
    messagingSenderId: '288869750518',
    projectId: 'university-system-24232',
    storageBucket: 'university-system-24232.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyzJFM8lkDVxc-E-MkaEEm-_PSCJgC1co',
    appId: '1:288869750518:ios:1c730945fb31e50c73bed7',
    messagingSenderId: '288869750518',
    projectId: 'university-system-24232',
    storageBucket: 'university-system-24232.firebasestorage.app',
    iosBundleId: 'com.example.univerisitySystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyzJFM8lkDVxc-E-MkaEEm-_PSCJgC1co',
    appId: '1:288869750518:ios:1c730945fb31e50c73bed7',
    messagingSenderId: '288869750518',
    projectId: 'university-system-24232',
    storageBucket: 'university-system-24232.firebasestorage.app',
    iosBundleId: 'com.example.univerisitySystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsRht_GM1V_5QftkYSDG18_zGfFy4KwnY',
    appId: '1:288869750518:web:876470516a4530b473bed7',
    messagingSenderId: '288869750518',
    projectId: 'university-system-24232',
    authDomain: 'university-system-24232.firebaseapp.com',
    storageBucket: 'university-system-24232.firebasestorage.app',
    measurementId: 'G-T4QNLCTEGK',
  );
}
